name: Enforce release-only into main
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - name: Fail unless head is a release/* branch
        run: |
          if [[ "${{ github.head_ref }}" != release/* ]]; then
            echo "Only release/* branches may be merged into main."
            exit 1
          fi
